### ISSUE TITLE
Demo doesn't work on Arduino Uno

### ISSUE THREAD

**Issue by adeev** [gpb01/SerialCmd#1]
The controller accepts the first command. However, to any second command it responds: Error command not found. Tested on Arduino Uno R3.

**Comment by gpb01** [comment]
Sorry, but ... I think you should have other kind of problems somewhere else.

The demo has been tested several times and works correctly (_... the library is already widely used in various real applications_) both on the whole AVR family (_UNO / MEGA / Leonardo / Yún_) and also on the SAMD family, STM32 and on Teensy.

Can you give more details? Thank you.

**Comment by gpb01** [comment]
Have you checked the serial monitor settings? Did you set for only CR and NOT CR/LF?

**Comment by adeev** [comment]
Board: Arduino Uno R3 purchased last week.
Library SerialCmd 1.0.7 installed by Arduino IDE
Code: Unmodified example SerialCmd_Demo.ino from SerialCmd/examples folder
Port settings 9600, NL&CR
Output: INFO: Program running on AVR ...
Input: LEDON
Output: OK
Input: LEDOF
Output: ERROR: Command not found.



The same behavior if I send LEDOF first. The program understands the first command but responds "ERROR: Command not found." to any valid following command.
I was thinking about debugging it myself but then I tried another library that worked right away. But I just wanted to let you know about the issue.

**Comment by gpb01** [comment]
And I repeat that there is NO problem, it is your wrong setting of the terminal emulator ... 
... port setting MUST NOT be NL&CR, but ONLY CR!
